### ISSUE TITLE
RuntimeError on Inter iRIS Xe / Ubuntu 23 computer, but SOME options work

### ISSUE THREAD

**Issue by kusmic** [PolyPhyHub/PolyPhy#74]
So during the NMSU 2023 workshop, I tried running the provided example '3d_discrete' pipeline and get the present error:

```
[Taichi] version 1.6.0, llvm 15.0.4, commit f1c6fbbd, linux, python 3.10.0
2023-12-13 14:28:37,795 - INFO - Loading input file... ../../data/csv/sample_3D_linW.csv None
2023-12-13 14:28:38,175 - INFO - Simulation domain min: (-498.44942169189454, -486.340283203125, -64.52593154907227)
2023-12-13 14:28:38,175 - INFO - Simulation domain max: (19.511767196655274, 453.21668701171876, 467.07646484375)
2023-12-13 14:28:38,175 - INFO - Simulation domain size: [517.96118889 939.55697021 531.60239639]
2023-12-13 14:28:38,175 - INFO - Number of agents: 1000000
2023-12-13 14:28:38,175 - INFO - Number of data points: 324901
2023-12-13 14:28:38,175 - INFO - Trace grid resolution: [282 512 289]
2023-12-13 14:28:38,175 - INFO - Deposit grid resolution: (282, 512, 289)
2023-12-13 14:28:38,175 - INFO - Vis resolution: (1280, 720)
[W 12/13/23 14:28:38.176 150007] [cuda_driver.cpp:load_lib@36] libcuda.so lib not found.
[Taichi] Starting on arch=vulkan
2023-12-13 14:28:38,277 - INFO - Agent sample: [-442.24393     398.22058      -6.5987897     0.44868344    1.8256238
    1.        ]
2023-12-13 14:28:38,279 - INFO - Total GPU memory allocated: 40 MB
[E 12/13/23 14:28:38.428 150007] [runtime.cpp:launch_kernel@553] Dispatch error : RhiResult(-3)


Traceback (most recent call last):
  File "/home/samirk/repos/PolyPhy/src/polyphy/polyphy.py", line 16, in <module>
    main()
  File "/home/samirk/repos/PolyPhy/src/polyphy/polyphy.py", line 12, in main
    CliHelper.parse_values(ppConfig)
  File "/home/samirk/repos/PolyPhy/src/polyphy/utils/cli_helper.py", line 230, in parse_values
    PolyPhy_3DDiscrete(ppConfig, args.batch_mode, args.num_iterations).start_simulation()
  File "/home/samirk/repos/PolyPhy/src/polyphy/pipelines/discrete3D.py", line 27, in __init__
    self.ppInternalData = PPInternalData_3DDiscrete(
  File "/home/samirk/repos/PolyPhy/src/polyphy/core/discrete3D.py", line 185, in __init__
    self.__init_internal_data__(ppKernels)
  File "/home/samirk/repos/PolyPhy/src/polyphy/core/discrete3D.py", line 127, in __init_internal_data__
    ppKernels.zero_field(self.deposit_field)
  File "/home/samirk/anaconda3/envs/polyphy/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 1033, in __call__
    return self._primal(self._kernel_owner, *args, **kwargs)
  File "/home/samirk/anaconda3/envs/polyphy/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 906, in __call__
    return self.runtime.compiled_functions[key](*args)
  File "/home/samirk/anaconda3/envs/polyphy/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 817, in func__
    raise e from None
  File "/home/samirk/anaconda3/envs/polyphy/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 814, in func__
    t_kernel(launch_ctx)
RuntimeError: [runtime.cpp:launch_kernel@553] Dispatch error : RhiResult(-3)
```

Reducing the quantities of -t, -x, and -y still produced this error (down to 52, 768, and 512 respectively). Batch mode seems to work correctly 

```
python polyphy.py 3d_discrete -f "data/csv/sample_3D_linW.csv" -t 32 -b -n 100
[Taichi] version 1.6.0, llvm 15.0.4, commit f1c6fbbd, linux, python 3.10.0
Batch mode activated!
Number of iterations: 100
2023-12-13 14:24:00,020 - INFO - Loading input file... ../../data/csv/sample_3D_linW.csv None
2023-12-13 14:24:00,398 - INFO - Simulation domain min: (-498.44942169189454, -486.340283203125, -64.52593154907227)
2023-12-13 14:24:00,398 - INFO - Simulation domain max: (19.511767196655274, 453.21668701171876, 467.07646484375)
2023-12-13 14:24:00,398 - INFO - Simulation domain size: [517.96118889 939.55697021 531.60239639]
2023-12-13 14:24:00,398 - INFO - Number of agents: 1000000
2023-12-13 14:24:00,398 - INFO - Number of data points: 324901
2023-12-13 14:24:00,398 - INFO - Trace grid resolution: [17 32 18]
2023-12-13 14:24:00,398 - INFO - Deposit grid resolution: (17, 32, 18)
2023-12-13 14:24:00,398 - INFO - Vis resolution: (1280, 720)
[W 12/13/23 14:24:00.399 149769] [cuda_driver.cpp:load_lib@36] libcuda.so lib not found.
[Taichi] Starting on arch=vulkan
2023-12-13 14:24:00,503 - INFO - Agent sample: [-176.32744    -71.63474     42.392937     1.7443166    1.6732621
    1.       ]
2023-12-13 14:24:00,505 - INFO - Total GPU memory allocated: 38 MB
2023-12-13 14:24:00,583 - INFO - Running MCPM... iteration 1 / 100
2023-12-13 14:24:00,827 - INFO - Running MCPM... iteration 2 / 100
2023-12-13 14:24:00,828 - INFO - Running MCPM... iteration 4 / 100
2023-12-13 14:24:00,828 - INFO - Running MCPM... iteration 5 / 100
2023-12-13 14:24:00,830 - INFO - Running MCPM... iteration 10 / 100
2023-12-13 14:24:00,832 - INFO - Running MCPM... iteration 20 / 100
2023-12-13 14:24:00,833 - INFO - Running MCPM... iteration 25 / 100
2023-12-13 14:24:00,840 - INFO - Running MCPM... iteration 50 / 100
2023-12-13 14:24:00,852 - INFO - Running MCPM... iteration 100 / 100
2023-12-13 14:24:00,852 - INFO - Storing solution data in data/fits/
```

The fits are present there.

**HOWEVER**, if I run:
`python polyphy.py 3d_discrete -f "data/csv/sample_3D_linW.csv" -t 160 -x 0 -y 0`

**A window opens and it works just fine, it seems.** I'm with Oskar and he is perplexed, too. Here is a dump on my GPU.

```
*-display                 
       description: VGA compatible controller
       product: Alder Lake-UP3 GT2 [Iris Xe Graphics]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 0c
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 mode=1920x1080 resolution=1920,1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:600-5ff iomemory:400-3ff irq:157 memory:6000000000-6000ffffff memory:4000000000-400fffffff ioport:3000(size=64) memory:c0000-dffff memory:4010000000-4016ffffff memory:4020000000-40ffffffff
```

Currently trying to find a way to dump driver information. Will comment when I find out.

**Comment by kusmic** [comment]
Added to the issue, batch mode does not work at a given agent resolution either. 

```
python polyphy.py 3d_discrete -f "data/halos_003.csv" -t 512 -b -n 100 -d 0.6
[Taichi] version 1.6.0, llvm 15.0.4, commit f1c6fbbd, linux, python 3.10.0
Batch mode activated!
Number of iterations: 100
2023-12-13 15:32:04,836 - INFO - Loading input file... ../../data/halos_003.csv None
2023-12-13 15:32:05,007 - INFO - Simulation domain min: (-0.8249640436093615, -0.8249566485603282, -0.8249468365800567)
2023-12-13 15:32:05,007 - INFO - Simulation domain max: (17.32497034072876, 17.3247501373291, 17.32471971511841)
2023-12-13 15:32:05,008 - INFO - Simulation domain size: [18.14993438 18.14970679 18.14966655]
2023-12-13 15:32:05,008 - INFO - Number of agents: 1000000
2023-12-13 15:32:05,008 - INFO - Number of data points: 148342
2023-12-13 15:32:05,008 - INFO - Trace grid resolution: [512 511 511]
2023-12-13 15:32:05,008 - INFO - Deposit grid resolution: (512, 511, 511)
2023-12-13 15:32:05,008 - INFO - Vis resolution: (1280, 720)
[W 12/13/23 15:32:05.008 159751] [cuda_driver.cpp:load_lib@36] libcuda.so lib not found.
[Taichi] Starting on arch=vulkan
2023-12-13 15:32:05,116 - INFO - Agent sample: [4.8392143  2.520035   5.19493    0.91232234 1.367478   1.        ]
2023-12-13 15:32:05,118 - INFO - Total GPU memory allocated: 38 MB
[E 12/13/23 15:32:05.512 159751] [runtime.cpp:launch_kernel@553] Dispatch error : RhiResult(-3)


Traceback (most recent call last):
  File "/home/samirk/repos/PolyPhy/src/polyphy/polyphy.py", line 16, in <module>
    main()
  File "/home/samirk/repos/PolyPhy/src/polyphy/polyphy.py", line 12, in main
    CliHelper.parse_values(ppConfig)
  File "/home/samirk/repos/PolyPhy/src/polyphy/utils/cli_helper.py", line 230, in parse_values
    PolyPhy_3DDiscrete(ppConfig, args.batch_mode, args.num_iterations).start_simulation()
  File "/home/samirk/repos/PolyPhy/src/polyphy/pipelines/discrete3D.py", line 27, in __init__
    self.ppInternalData = PPInternalData_3DDiscrete(
  File "/home/samirk/repos/PolyPhy/src/polyphy/core/discrete3D.py", line 185, in __init__
    self.__init_internal_data__(ppKernels)
  File "/home/samirk/repos/PolyPhy/src/polyphy/core/discrete3D.py", line 127, in __init_internal_data__
    ppKernels.zero_field(self.deposit_field)
  File "/home/samirk/anaconda3/envs/polyphy/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 1033, in __call__
    return self._primal(self._kernel_owner, *args, **kwargs)
  File "/home/samirk/anaconda3/envs/polyphy/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 906, in __call__
    return self.runtime.compiled_functions[key](*args)
  File "/home/samirk/anaconda3/envs/polyphy/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 817, in func__
    raise e from None
  File "/home/samirk/anaconda3/envs/polyphy/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 814, in func__
    t_kernel(launch_ctx)
RuntimeError: [runtime.cpp:launch_kernel@553] Dispatch error : RhiResult(-3)
```

So I can't go above a given -t, and so far I found out that value is 200.

**Comment by Abhinavcode13** [comment]
Since #95 has already addressed this, I'm closing this issue.
